name: social_swap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.4
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  fluttertoast: ^8.2.12
  http: ^1.3.0
  provider: ^6.1.2
  intl: ^0.19.0
  google_mlkit_translation: ^0.12.0
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  iconsax: ^0.0.8
  lottie: ^3.3.1
  curved_navigation_bar: ^1.0.6
  font_awesome_flutter: ^10.8.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  