name: social_swap
description: A modern social media application with AI-powered interactions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  provider: ^6.1.1
  google_fonts: ^6.1.0
  iconsax: ^0.0.8
  http: ^1.1.0
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  curved_navigation_bar: ^1.0.3
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  google_mlkit_translation: ^0.13.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  video_player: ^2.8.2
  visibility_detector: ^0.4.0+2
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/categories/
    - assets/carousel/
    - assets/lottie/