// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC09k0xabUc8WnADfIghnFwnEb1tUReHw',
    appId: '1:374369228221:android:73bcf85742300807a6eed4',
    messagingSenderId: '374369228221',
    projectId: 'shop-ease-bc288',
    storageBucket: 'shop-ease-bc288.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_YR85r1C47isvPi3933Ih-bllEQtZCE',
    appId: '1:374369228221:ios:784b72c246cabedca6eed4',
    messagingSenderId: '374369228221',
    projectId: 'shop-ease-bc288',
    storageBucket: 'shop-ease-bc288.firebasestorage.app',
    iosBundleId: 'com.example.socialSwap',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACvmOprFO6fPynRmQXLjI8vxECrNOj4go',
    appId: '1:374369228221:web:572864c77c047516a6eed4',
    messagingSenderId: '374369228221',
    projectId: 'shop-ease-bc288',
    authDomain: 'shop-ease-bc288.firebaseapp.com',
    storageBucket: 'shop-ease-bc288.firebasestorage.app',
    measurementId: 'G-PK044BZLC4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_YR85r1C47isvPi3933Ih-bllEQtZCE',
    appId: '1:374369228221:ios:784b72c246cabedca6eed4',
    messagingSenderId: '374369228221',
    projectId: 'shop-ease-bc288',
    storageBucket: 'shop-ease-bc288.firebasestorage.app',
    iosBundleId: 'com.example.socialSwap',
  );

}